### ISSUE TITLE
CameraCaptureActivity startRecording 报错

### ISSUE THREAD

**Issue by ruanchaohouzi** [DiskyZhs/PinFilter#1]
点击页面CameraCaptureActivity中的按钮startRecording 报错，问下为什么？？？谢谢
11-13 15:32:06.196 17249-17339/com.pinssible.camerarecorder.camerarecorderdemo E/AndroidRuntime: FATAL EXCEPTION: TextureMovieEncoder
    Process: com.pinssible.camerarecorder.camerarecorderdemo, PID: 17249
    java.lang.RuntimeException: format changed twice
        at com.pinssible.librecorder.recorder.AndroidMuxer.addTrack(AndroidMuxer.java:49)
        at com.pinssible.librecorder.recorder.AndroidEncoder.drainEncoder(AndroidEncoder.java:108)
        at com.pinssible.librecorder.recorder.VideoEncoder.handleFrameAvailable(VideoEncoder.java:322)
        at com.pinssible.librecorder.recorder.VideoEncoder.access$200(VideoEncoder.java:66)
        at com.pinssible.librecorder.recorder.VideoEncoder$EncoderHandler.handleMessage(VideoEncoder.java:281)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at com.pinssible.librecorder.recorder.VideoEncoder.run(VideoEncoder.java:240)
        at java.lang.Thread.run(Thread.java:776)

**Comment by Waychel** [comment]
> 
> 
> 点击页面CameraCaptureActivity中的按钮startRecording 报错，问下为什么？？？谢谢
> 11-13 15:32:06.196 17249-17339/com.pinssible.camerarecorder.camerarecorderdemo E/AndroidRuntime: FATAL EXCEPTION: TextureMovieEncoder
> Process: com.pinssible.camerarecorder.camerarecorderdemo, PID: 17249
> java.lang.RuntimeException: format changed twice
> at com.pinssible.librecorder.recorder.AndroidMuxer.addTrack(AndroidMuxer.java:49)
> at com.pinssible.librecorder.recorder.AndroidEncoder.drainEncoder(AndroidEncoder.java:108)
> at com.pinssible.librecorder.recorder.VideoEncoder.handleFrameAvailable(VideoEncoder.java:322)
> at com.pinssible.librecorder.recorder.VideoEncoder.access$200(VideoEncoder.java:66)
> at com.pinssible.librecorder.recorder.VideoEncoder$EncoderHandler.handleMessage(VideoEncoder.java:281)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:156)
> at com.pinssible.librecorder.recorder.VideoEncoder.run(VideoEncoder.java:240)
> at java.lang.Thread.run(Thread.java:776)

Muxer类 mExpectedNumTracks = 1 修改为 =2 即可。
